const QUESTOES_QUIZ = [
    {
        questao: 'Qual é o elhor protagonista dos animes?',
        a: 'Itadori',
        b: 'Naruto',
        c: 'Saitama',
        d: 'Denji',
        correta: 'd',
    },
    {
        questao: 'No minecraft Pixelmon, como se faz para evoluir um inkay?',
        a: 'deve trocar ele com um amigo',
        b: 'deve virar o munitor de cabeça para baixo',
        c: 'se deve estar a uma altura superior a 137 blocos e com o nivel superior a 29',
        d: 'ele não evolui',
        correta: 'c',
    },
    {
        questao: 'quantos capitulos tem chainsaw man?',
        a: '179',
        b: '180',
        c: '190',
        d: '169',
        correta: 'a',
    },
    {
        questao: 'qual entre esses eu prefiro?',
        a: 'refri no ponto',
        b: 'açai completo',
        c: 'suco natural',
        d: 'churrasco',
        correta: 'b',
    },
    {
        questao: 'qual é a formula de baskara?',
        a: 'b²-4ac',
        b: 'a²+b²=c²',
        c: 'sim',
        d: '-b+-(raiz quadrada de delta)/2.a',
        correta: 'd',
    },
    {
        questao: 'qual o nome do pénultimo boss de resident evil 4 remake?',
        a: 'albert wesker',
        b: 'ada wong',
        c: 'leon scoot kened',
        d: 'krauser',
        correta: 'd',
    },
    {
        questao: 'quantos residents evil (numerados) existem?',
        a: '4',
        b: '7',
        c: '8',
        d: '9',
        correta: 'c',
    },
    {
        questao: 'quantos dias tem esse ano?',
        a: '366',
        b: '365',
        c: '360',
        d: '5 dias, pq parece que ainda é março, pelamor de deus, tempo para um pouco',
        correta: 'a',
    },
    {
        questao: 'qual o meu jogo favorito',
        a: 'minecraft',
        b: 'god of war',
        c: 'resident evil 4 remake',
        d: 'dying light',
        correta: 'd',
    },
    {
        questao: 'o que eu vou fazer quando chegar em casa?',
        a: 'comer',
        b: 'todas as opções',
        c: 'chorar com medo da escola',
        d: 'dormir',
        correta: 'b',
    },
]